[package]
name = "ucalc_numbers"
version.workspace = true
edition.workspace = true

[features]
default = ["f64"]
f16 = ["float"]
f32 = ["float"]
f64 = ["float"]
f128 = ["float"]
float = []
rug = ["dep:rug"]
fastnum = ["dep:fastnum", "float"]
units = []

[dependencies]
rug = {version="1.28.1",optional=true, default-features=false, features=["complex","float","integer","rand","std"]}
fastnum = {version = "0.7.4",optional=true}
