[package]
name = "ucalc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true

[features]
default = ["f64", "complex", "raw"]
f16 = ["ucalc_lib/f16"]
f32 = ["ucalc_lib/f32"]
f64 = ["ucalc_lib/f64"]
f128 = ["ucalc_lib/f128"]
rug = ["ucalc_lib/rug"]
fastnum = ["ucalc_lib/fastnum"]
units = ["ucalc_lib/units"]
vector = ["ucalc_lib/vector"]
matrix = ["ucalc_lib/matrix"]
list = ["ucalc_lib/list"]
complex = ["ucalc_lib/complex"]
raw = ["dep:termion"]

[dependencies]
ucalc_lib = {workspace = true}
termion = {version = "4.0.6", optional=true}