on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Temporarily modify the rust toolchain version
      run: rustup override set nightly
    - name: Install nightly components
      run: |
        rustup component add rust-src
        rustup component add rustfmt
        rustup component add clippy
    - name: Format
      run: cargo fmt --check
    - name: Clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --verbose --no-default-features --features "f64"
    - name: Run tests
      run: cargo test --verbose --no-default-features --features "f64"
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Temporarily modify the rust toolchain version
      run: rustup override set nightly
    - name: Install nightly components
      run: rustup component add rust-src
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: ucalc-linux
        path: target/release/ucalc
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Temporarily modify the rust toolchain version
      run: rustup override set nightly
    - name: Install nightly components
      run: rustup component add rust-src
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: ucalc.exe
        path: target/release/ucalc.exe
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Temporarily modify the rust toolchain version
      run: rustup override set nightly
    - name: Install nightly components
      run: rustup component add rust-src
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v4
      with:
        name: ucalc-macos
        path: target/release/ucalc
